name: Import Docker Hub secrets
on:
  repository_dispatch:
    types: [import-docker-secrets]
jobs:
  import:
    name: store docker hub credentials
    runs-on: ubuntu-latest
    steps:
      - name: set repository secrets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          printf '%s' '${{ github.event.client_payload.username }}' | gh secret set DOCKERHUB_USERNAME --repo agentvoiceresponse/avr-sts-xai --body-file -
          printf '%s' '${{ github.event.client_payload.password }}' | gh secret set DOCKERHUB_PASSWORD --repo agentvoiceresponse/avr-sts-xai --body-file -
