name: Import Docker Hub secrets
on:
  repository_dispatch:
    types: [import-docker-secrets]
jobs:
  import:
    name: store docker hub credentials
    runs-on: ubuntu-latest
    steps:
      - name: set repository secrets
        env:
          DOCKERHUB_USERNAME: ${{ github.event.client_payload.username }}
          DOCKERHUB_PASSWORD: ${{ github.event.client_payload.password }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh secret set DOCKERHUB_USERNAME --body "$DOCKERHUB_USERNAME"
          gh secret set DOCKERHUB_PASSWORD --body "$DOCKERHUB_PASSWORD"
